# Generated by Django 6.0.4 on 2026-04-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target', models.CharField(choices=[('all', 'All Employees'), ('activity', 'Specific Activity')], default='all', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.CharField(default='Admin', max_length=100)),
                ('recipients', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Broadcast Message',
                'verbose_name_plural': 'Broadcast Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('interval_days', models.PositiveIntegerField(help_text='Days before activity to send reminder (e.g. 7, 3, 1)', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reminder Configuration',
                'verbose_name_plural': 'Reminder Configurations',
                'ordering': ['interval_days'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('notification_type', models.CharField(choices=[('confirmation', 'Registration Confirmation'), ('reminder', 'Activity Reminder'), ('update', 'Activity Update'), ('cancellation', 'Cancellation'), ('broadcast', 'Admin Broadcast')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('fail_reason', models.TextField(blank=True, default='')),
                ('ngo_id', models.IntegerField(blank=True, null=True)),
                ('ngo_name', models.CharField(blank=True, max_length=100)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notification.broadcast')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
