# Generated by Django 6.0.4 on 2026-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='ngo_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('confirmation', 'Registration Confirmation'), ('reminder', 'Activity Reminder'), ('update', 'Activity Update'), ('cancellation', 'Cancellation'), ('broadcast', 'Admin Broadcast'), ('switch', 'Activity Switch'), ('verification', 'Email Verification')], max_length=20),
        ),
    ]
